src/main/java/cucumber/pageObjects/ActivePools.java, src/main/java/cucumber/pageObjects/JurorRecord.java, src/main/java/cucumber/pageObjects/TrialsAndAttendance.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/java/cucumber/steps/StepDef_trialsAndAttendance.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5072.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5687.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-6163.feature
=> jcde-5mar-merge

config/owasp/suppressions.xml
=> CVE tidy up

src/main/java/cucumber/pageObjects/CourtJurorRecord.java, src/main/java/cucumber/pageObjects/Groups.java, src/main/java/cucumber/pageObjects/SharedDriver.java, src/test/java/cucumber/steps/StepDef_groups.java, src/test/java/cucumber/steps/StepDef_trialsAndAttendance.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4949-5766.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4956-4679.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5072.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5405-5407-Resend-Deferal-Granted-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5692-reminder to attend.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5694-failed to attend.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5697-attendance date and time changed.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5698-attendance time change.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5702-complete not needed.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5703-next-due-at-court-date.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5705-on call.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5707-contact the court.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5711-selected for a panel.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6073-bad weather.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6075-check your email.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6077-bring lunch.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6079-excused.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-4358-BUREAU-reassign warnings.feature
=> jcde-8mar-merge

Jenkinsfile_CNP, build.gradle, src/test/java/cucumber/testRunner/TestRunner_Expenses.java, src/test/java/cucumber/testRunner/TestRunner_Features.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformation.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformationMulti.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformationWIP.java, src/test/java/cucumber/testRunner/TestRunner_NewSchemaConverted.java, src/test/java/cucumber/testRunner/TestRunner_Regression.java, src/test/java/cucumber/testRunner/TestRunner_RegressionSingle.java, src/test/java/cucumber/testRunner/TestRunner_RegressionWelsh.java
Break up test pack into smaller chunks
```
[ ] Yes
[x] No
```
=> Split up tests

build.gradle
Correct error in ENV VAR name
```
[ ] Yes
[x] No
```
=> correct Regression flag

src/test/java/cucumber/steps/StepDef_hooks.java
=> change screenshot zoom on error to 100%

Jenkinsfile_nightly
Configure nightly job to run and point to 'test'
```
[ ] Yes
[x] No
```
=> configure nightly

Jenkinsfile_CNP, Jenkinsfile_nightly
=> add modcourt password pull

src/main/java/cucumber/utils/WaitUtils.java, src/test/java/cucumber/testRunner/TestRunner_Expenses.java, src/test/java/cucumber/testRunner/TestRunner_Features.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformation.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformationMulti.java, src/test/java/cucumber/testRunner/TestRunner_JurorTransformationWIP.java, src/test/java/cucumber/testRunner/TestRunner_NewSchemaConverted.java, src/test/java/cucumber/testRunner/TestRunner_Regression.java, src/test/java/cucumber/testRunner/TestRunner_RegressionSingle.java, src/test/java/cucumber/testRunner/TestRunner_RegressionWelsh.java, src/test/java/cucumber/testRunner/TestRunner_Shakedown.java, src/test/java/cucumber/testRunner/TestRunner_SmokeTest.java, src/test/java/cucumber/testRunner/admin/TestRunner_INT_Features_ADMIN.java, src/test/java/cucumber/testRunner/admin/TestRunner_INT_Regression_ADMIN.java, src/test/java/cucumber/testRunner/admin/TestRunner_INT_SmokeTest_ADMIN.java
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
Remove rerun failed scenarios flag from runners and decrease wait times
```
[ ] Yes
[ x] No
```
=> remove rerun failed scenarios flags and reduce implicit wait time

src/main/java/cucumber/pageObjects/Expenses.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_expenses.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6110.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6111.feature
=> JM-6111 and JM-6110, also an amendment to clean steps to avoid errors

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3803-3814-grant_excusal_digital.feature
=> JM-3814: add tests for grant excusal from juror record

src/test/resources/cucumber/features/9_Week_Comms_StraightThrough.feature, src/test/resources/cucumber/features/Bureau_Edit_MHQs_Over2k.feature, src/test/resources/cucumber/features/JDB-4172 Comms Welsh Flag.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-2486-assign-replies.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3000_assign_to_colleague.feature, src/test/resources/cucumber/features/REGRESSION_JDB-4242_3rd_Does_Not_Update_Juror.feature, src/test/resources/cucumber/features/Third_Party_Phone_Not_Juror_Phone.feature, src/test/resources/cucumber/features/dashboard/Dashboard.feature, src/test/resources/cucumber/features/regression/CommsGeneration.feature, src/test/resources/cucumber/features/regression/REGRESSION_Bureau_B_Search.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_3rd_Deceased.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_MentalHealthQuestionsSeparation.feature, src/test/resources/cucumber/features/regression/REGRESSION_JDB-3845.feature, src/test/resources/cucumber/features/regression/REGRESSION_JDB-5345-spaces in null values.feature, src/test/resources/cucumber/features/regression/REGRESSION_Juror_Ineligiblity.feature, src/test/resources/cucumber/features/regression/REGRESSION_ReplyTypesIndicator.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_AutoAllocation.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_C_Re_Allocate.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_StraightThrough.feature, src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature, src/test/resources/environment.properties
=> DB - changed all references to SYSTEM to MODTESTBUREAU

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5965.feature
=> extra scenario to existing exemption letter script

src/main/java/cucumber/pageObjects/PoolOverview.java, src/test/java/cucumber/steps/StepDef_courtJurorRecord.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature, src/test/resources/cucumber/features/skeletonTest/JM-251.feature
=> JM-251 JM-252 test fixes

src/main/java/cucumber/pageObjects/ActivePools.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3803-3814-grant_excusal_digital.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3812-3893-paper-mark-juror-as-deceased.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Validation_and_Errors.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Validation_and_Errors.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3671.feature
=> JM-252 JM-3671 JM-3803 JM-3812 test fixes

src/main/java/cucumber/pageObjects/SummonsReply.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/9_Week_Comms_StraightThrough.feature, src/test/resources/cucumber/features/JDB-4172 Comms Welsh Flag.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-4103.feature, src/test/resources/cucumber/features/REGRESSION_JDB-4242_3rd_Does_Not_Update_Juror.feature, src/test/resources/cucumber/features/REGRESSION_SuperUrgentSendToCourt.feature, src/test/resources/cucumber/features/dashboard/Dashboard.feature, src/test/resources/cucumber/features/regression/REGRESSION_4539.feature, src/test/resources/cucumber/features/regression/REGRESSION_4546.feature, src/test/resources/cucumber/features/regression/REGRESSION_EditableSummons.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_Deferral.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_RA.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_3rd_Deferral.feature, src/test/resources/cucumber/features/regression/REGRESSION_JDB-3845.feature, src/test/resources/cucumber/features/regression/REGRESSION_JDB-5345-spaces in null values.feature, src/test/resources/cucumber/features/regression/REGRESSION_Secrets_Changes.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_A.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_AutoAllocation.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_RecordsUpdatedInJurorBeforeJD.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_StraightThrough.feature
=> DB - BAU refactoring

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3812-3893-paper-mark-juror-as-deceased.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3826.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3899-decline-deferral-paper-juror-record.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4186-Straight-Through-Summons-Reply-Paper.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/Testing paper summons access.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Validation_and_Errors.feature
=> JM-252 JM-3899 JM-3826 JM-3812 JM-4186 test fixes

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4222.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4254.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4368-Jury-Officer-can-manually-run-police-check.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5687.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-4681-COURT.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Validation_and_Errors.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3351.feature, src/test/resources/db/001_users.sql
=> JM-252 JM-351 JM-4222 JM-4254 JM-4368 JM-5687 test fixes

Jenkinsfile_CNP, Jenkinsfile_nightly
Rename build
```
[ ] Yes
[x] No
```
=> rename build to show target env

src/main/java/cucumber/pageObjects/JurorRecord.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6261.feature
=> JM-6261 - Resend initial summons letter via pool

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6064.feature
=> adding to work in progress

src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/Testing paper summons access.feature
=> JM-4079 test fixes

src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-4365.feature
Feature JM-4365-Scenario Outline: To confirm all the jurors  attendance on the day -moved to WIP
```
[ ] Yes
[ x] No
```
=>   JM-4365 - one scenario moved to WIP

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6261.feature
=> JM-6533 - update tests due to database field change

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5592-5594-Withdrawal-Letter.feature
=> Withdrawal letter scripts for Bureau and Court user

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4184.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5086-5087-5088-5628-Create-Juror-Record.feature
=> extra scenarios to JM-4184 after bug fix, removal of some WIP tags

src/test/java/cucumber/steps/StepDef_expenses.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6062-6311.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-5070-4362-ChangeAndConfirm-Jurors-AttendanceDate.feature
=> JM-6066 - add test for recalculate expenses button

src/main/java/cucumber/pageObjects/JurorRecord.java, src/main/java/cucumber/testdata/DatabaseTester.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5405-5407-Resend-Deferal-Granted-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5409-5411-Resend-Deferal-Refusal-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5588-5590-Resend-postponementLetter.feature
Feature/JM-5590 5411 and 5407 moved from WIP to ready
```
[ ] Yes
[ X] No
```
=> Feature/JM-5590 5411 and 5407 moved from WIP to ready

src/main/java/cucumber/pageObjects/Expenses.java, src/main/java/cucumber/pageObjects/SharedDriver.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/java/cucumber/steps/StepDef_expenses.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6064.feature
Merge 6064 changes to master
```
[ ] Yes
[x] No
```
=> Ticket 6064 to merge

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/dashboard/Dashboard.feature, src/test/resources/cucumber/features/dashboard/Dashboard_Content.feature
=> DB - BAU Dashboard tests refactor

src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5409-5411-Resend-Deferal-Refusal-Letter.feature
=> DB - fixed the deferral refused letter tests

src/main/java/cucumber/pageObjects/Expenses.java, src/test/java/cucumber/steps/StepDef_expenses.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6114.feature
=> JM-6114 Test

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3686.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4247.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4249.feature
=> DB - changed the reasonable adj code in the test to match the new codes

src/main/java/cucumber/pageObjects/PoolRequests.java
=> Fix issue where pool is not found even though it exists

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/Regression_Work_AllocationSuperUrgent.feature
=> DB - add insert juror_audit row to court owned records

src/test/resources/cucumber/features/REGRESSION_English_1st_ChangeAddress_Bureau.feature
=> DB - updated to reflect new court catchment warning

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5963.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6259.feature
=> JM-6259 summons reminder, JM-5963 cert of attendance

src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature
=> Updates smoke test to work after db reset

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java
=> DB - add ATTEND_TIME to pool inserts as per defect JM-6967

src/test/resources/db/001_users.sql, src/test/resources/db/004_judge.sql
=> DB - added SHREWSBURY court user to data load

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4368-Jury-Officer-can-manually-run-police-check.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5409-5411-Resend-Deferal-Refusal-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6261.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3351.feature
=> Multipack fixes

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5963.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-2485.feature
=> Fix failing tests for letter printing and browsing pools

src/test/resources/drivers/chromedriver-linux64/LICENSE.chromedriver
=> update chromedriver to 124.0.6367.60

Jenkinsfile_nightly, src/test/resources/environment.properties
while we are using 'test' for perf testing, using ithc for nightly automation runs
```
[ ] Yes
[ ] No
```
=> temp add ithc to nightly default

src/main/java/cucumber/pageObjects/NavigationShared.java, src/test/java/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature
=> Smoketest fix

src/main/java/cucumber/pageObjects/NavigationShared.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5967-Show-Cause-Letter.feature
update the 5967 script and  make it run  and passed
```
[ ] Yes
[ ] No
```
=> Ticket 5967 to update

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/Bureau_Search_Invalid_Input.feature, src/test/resources/cucumber/features/Third_Party_Phone_Not_Juror_Phone.feature, src/test/resources/cucumber/features/regression/REGRESSION_Bureau_E_Staff.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_Excusal.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_Overage_SkipMainContent.feature, src/test/resources/cucumber/features/regression/REGRESSION_JDB-3845.feature
=> DB - BAU - various updates to reflect new functional flows

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5405-5407-Resend-Deferal-Granted-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5409-5411-Resend-Deferal-Refusal-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5413-Resend-Excusal-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5417-Resend-Excusal-Refused-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5588-5590-Resend-postponementLetter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5592-5594-Withdrawal-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5687.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5963.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-4681-COURT.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature
=> Multipack failures - fix

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4222.feature
=> Fix for JM-4222 failure

src/test/resources/cucumber/features/English_3rd_BackLink.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_Deferral.feature, src/test/resources/cucumber/features/regression/REGRESSION_HTML_Response_Summary.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature
=> DB - Various BAU fixes

src/main/java/cucumber/pageObjects/JurorRecord.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6214-DisqualificationCode.feature
=> Feature/JM-6214 Merge to master

build.gradle, src/main/java/cucumber/pageObjects/NavigationShared.java, src/main/java/cucumber/pageObjects/SharedDriver.java, src/main/java/cucumber/pageObjects/WebDriveDecorator.java, src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature
Fixed an issue with selenium upgrade
```
[ ] Yes
[X] No
```
=> Selenium upgrade fix

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6081-6083.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6388.feature
=> JM-6803 Fix > Tag and placing in wip

src/main/java/cucumber/pageObjects/SharedDriver.java, src/main/java/cucumber/pageObjects/WebDriveDecorator.java, src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature
=> Driver updates

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5670.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5672.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Validation_and_Errors.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Validation_and_Errors.feature
=> Refactor failing test

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4222.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-4958-4954-4955-complete-uncomplete-service.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5072.feature
=> test fixes for 5072, 4954, and 4222 scripts

src/main/java/cucumber/pageObjects/SummonsReply.java, src/test/java/cucumber/steps/StepDef_response.java, src/test/resources/cucumber/features/REGRESSION_Bureau_Process_Options.feature, src/test/resources/cucumber/features/regression/REGRESSION_EditableSummons.feature, src/test/resources/cucumber/features/regression/REGRESSION_ReplyTypesIndicator.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_A.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_AutoAllocation.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/db/001_users.sql
=> DB - various

src/main/java/cucumber/pageObjects/PoolRequests.java
=> additional logging to try and identify why the test is failing

src/main/java/cucumber/pageObjects/PoolRequests.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-4681-COURT.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Navigation.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Validation_and_Errors.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Validation_and_Errors.feature
=> Refactor get pool request by number

src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-4681-COURT.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature
…st causing failure
```
[ ] Yes
[ ] No
```
=> change user to user correct court for test

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-2895-super-urgent-summons-paper-reply.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-BUREAU_Validation_and_Errors.feature
=> Fixed tests

src/main/java/cucumber/pageObjects/PoolRequests.java
=> change locator to stop conflict and return exact element

src/main/java/cucumber/pageObjects/SummonsReply.java, src/test/java/cucumber/steps/StepDef_summoningprogress.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3686.feature
=> fix for not finding element

src/main/java/cucumber/pageObjects/JurorRecordSearch.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/smoketest/SmokeTest_buraeu.feature
=> DB - fixed the smoketest

src/test/resources/cucumber/features/REGRESSION_Bureau_Process_Options.feature, src/test/resources/cucumber/features/REGRESSION_SuperUrgentSendToCourt.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_Excusal.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_CookiesPrivacyPolicy.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_RecordsUpdatedInJurorBeforeJD.feature
=> DB - various fixes and moved some into @Features

src/test/resources/cucumber/features/REGRESSION_JDB-4242_3rd_Does_Not_Update_Juror.feature, src/test/resources/cucumber/features/regression/REGRESSION_English_1st_StraightThrough.feature, src/test/resources/cucumber/features/regression/REGRESSION_ReplyTypesIndicator.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature
=> DB - few more

src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-5070-4362-ChangeAndConfirm-Jurors-AttendanceDate.feature
=> script amendment for JM-5070

src/main/java/cucumber/pageObjects/JurorRecord.java, src/main/java/cucumber/pageObjects/PoolOverview.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/java/cucumber/steps/StepDef_navigation.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6259.feature
=> fix for selecting correct summoned juror

src/main/java/cucumber/pageObjects/SummonsReply.java, src/main/java/cucumber/pageObjects/ViewSummonsReply.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-3368-super urgent paper reponse.feature
=> Fixes and cleaning unused step

src/main/java/cucumber/pageObjects/PoolRequests.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-252-COURT_Navigation.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3351.feature
=> multiple test fixes

src/test/java/cucumber/steps/StepDef_response.java, src/test/resources/cucumber/features/English_1st_MobileNumberFocus.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_RecordsUpdatedInJurorBeforeJD.feature
=> DB - BAU refactors

src/main/java/cucumber/pageObjects/NavigationShared.java, src/test/java/cucumber/steps/StepDef.java, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_AutoAllocation.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_CookiesPrivacyPolicy.feature
=> DB - BAU refactors - cookies

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_DatabaseNewSchema.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5072.feature
=> fix for ongoing dismissal issue

src/main/java/cucumber/pageObjects/NavigationShared.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-5070-4362-ChangeAndConfirm-Jurors-AttendanceDate.feature
=> removal of WIP tag

src/main/java/cucumber/pageObjects/SummonsReply.java
=> fixing error with locator

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java
=> fixing error with police_check being null. changed to NOT_CHECKED

src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3351.feature
=> changing method of inputting filter

Jenkinsfile_nightly
=> JM-7303: enable all bau tests for nightly

src/main/java/cucumber/pageObjects/TrialsAndAttendance.java, src/test/java/cucumber/steps/StepDef_trialsAndAttendance.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6081-6083.feature
=> adding created juror from pool, conflicting data fix

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5405-5407-Resend-Deferal-Granted-Letter.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5409-5411-Resend-Deferal-Refusal-Letter.feature
=> conflicting data fix

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5692-reminder to attend.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5694-failed to attend.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5697-attendance date and time changed.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5698-attendance time change.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5700-complete attend.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5702-complete not needed.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5703-next-due-at-court-date.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5705-on call.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5707-contact the court.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5709.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5711-selected for a panel.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6073-bad weather.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6075-check your email.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6077-bring lunch.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6079-excused.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6081-6083.feature
=> move messages back to multi

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5869.feature
=> additional filtering, record wasn't appearing in limited list of 100

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/java/cucumber/steps/StepDef_trialsAndAttendance.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-5054- juryOfficerReturnRemovingPanelmember.feature
=> DB - fixes to JM-5054 tests

src/main/java/cucumber/pageObjects/NavigationShared.java
=> locator element fix

Jenkinsfile_CNP, Jenkinsfile_nightly
try cron on CNP and cater for PRs
```
[ ] Yes
[ x] No
```
=> try cron on CNP and cater for PRs

Jenkinsfile_CNP, Jenkinsfile_nightly
Remove timer on Jenkinsfile_CNP and try 2 branches on nightly
```
[ ] Yes
[x] No
```
=> Remove timer on Jenkinsfile_CNP and try 2 branches on nightly

src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-6163.feature
=> small fix for non attendance day script

Jenkinsfile_nightly
correct buildname
```
[ ] Yes
[ x] No
```
=> Correct buildname

Jenkinsfile_CNP, Jenkinsfile_nightly
enhance buildname
```
[ ] Yes
[x] No
```
=> Buildname enhancement

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5687.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5705-on call.feature, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-5709.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-5070-4362-ChangeAndConfirm-Jurors-AttendanceDate.feature
=> fixes for tests in multi

src/test/resources/cucumber/features/regression/REGRESSION_JDB-4562_Def_Dates_Messages.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_ErrorChecks.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_Excusal.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_3rd_Excusal.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_3rd_Underage.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_4546.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_AccountLocked.feature, src/test/resources/cucumber/features/regressionWelsh/WelshCharacterChecks.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_1st_1000_CharGuidance.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_1st_BetaBanner.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_1st_CJS_Checks.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_3rd_1000_CharGuidance.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_3rd_BetaBanner.feature, src/test/resources/cucumber/features/regressionWelsh/Welsh_3rd_MoreJurorDetails.feature
=> DB - refactored some bau welsh tests

Jenkinsfile_CNP, Jenkinsfile_nightly
=> remove secrets loading

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java
=> update bult_print_data test sql

src/test/resources/db/001_users.sql
=> update test sql

src/test/resources/cucumber/features/expenses/expenses_Welsh_JDB-4342.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_A.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_Bureau_New.feature, src/test/resources/cucumber/features/regressionSingle/REGRESSION_CookiesPrivacyPolicy.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_Underage.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_3rd_Deferral.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_3rd_ErrorChecks.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_3rd_StraightThrough_EmailCheck.feature, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_4533.feature
=> DB - refactored some bau welsh tests and updated the cookies tests

src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java
=> DB - updated insert digital summons reply so that reply_type is not null

Jenkinsfile_nightly
=> switch nightly to evening running

Jenkinsfile_nightly
=> fix nightly cron

build.gradle
Reverts hmcts/juror-automation-tests#238
=> Revert "Update dependency io.github.prashant-ramcharan:courgette-jvm to v6.14.0"

Jenkinsfile_CNP, Jenkinsfile_nightly
archive html files
```
[ ] Yes
[x] No
```
=> archive html files

src/main/java/cucumber/testdata/DatabaseTester.java, src/main/java/cucumber/testdata/DatabaseTesterNewSchemaDesign.java, src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-6064.feature, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3987-Bureau-monitor-pool-progress.feature
=> test fixes

src/test/resources/drivers/chromedriver-linux64/LICENSE.chromedriver
=> update chrome driver

src/main/java/cucumber/testdata/DatabaseTester.java, src/test/java/cucumber/steps/StepDef_jurorpool.java, src/test/java/cucumber/steps/StepDef_summoningprogress.java, src/test/resources/cucumber/features/Modernisation/PoolManagement/JM-3989-3993-BUREAU-reassign-juror-from-juror-record.feature
=> Cf test fixes for summoning progress

src/test/java/cucumber/steps/StepDef.java
=> login step fixes

src/test/resources/cucumber/features/Modernisation.jurorResponses/JM-2894-3367-4258-paper-summons.feature
Updated error code text
```
[ ] Yes
[X] No
```
=> Updated error code text

src/test/java/cucumber/steps/StepDef_jurorRecord.java, src/test/resources/cucumber/features/regressionWelsh/REGRESSION_Welsh_1st_Underage.feature
=> welsh dob fix

src/test/resources/drivers/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver
=> update to chromedriver 130

src/test/resources/drivers/chromedriver-linux64/THIRD_PARTY_NOTICES.chromedriver
=> bump to chromedriver 132.0.6834.83
